version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - pgadmin
    ports:
      - "5003:80"
    networks:
      - identity-network

  postgres:
    image: postgres
    container_name: identity-postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - identity-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: identity-pgadmin4_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5555:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - identity-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  identity-network:
    driver: bridge
