version: "3.8"

services:
  catalog_cache:
    image: redis/redis-stack
    container_name: catalog_cache
    ports:
      - 5103:6379
      - 5104:8001

  catalog_database:
    image: mongo
    container_name: catalog_database
    restart: unless-stopped
    ports:
      - 5102:27017
    volumes:
      - catalog-database:/data/db

  identity_database:
    image: mysql
    container_name: identity_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_PASSWORD=passwd
      - MYSQL_DATABASE=identity
      - MYSQL_TCP_PORT=5002
    volumes:
      - identity-database:/var/lib/mysql
    ports:
      - 5002:5002

volumes:
  catalog-database:
  identity-database:
