version: "3.8"

services:
  paymentdatabase:
    image: postgres
    container_name: payment_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - payment-database:/var/lib/postgresql/data

  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    container_name: payment_service
    build:
      context: .
      dockerfile: Services/PaymentService/PaymentService.API/Dockerfile.Development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/PaymentService.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ConnectionStrings:DefaultConnection=Server=host.docker.internal;Port=5432;Database=mm-payment;User Id=postgres;Password=postgres
      - Tenants__0__Name=Tenant A
      - Tenants__0__TenantId=tenant-a
      - Tenants__0__ConnectionString=Server=host.docker.internal;Port=5432;Database=payment-tenant-a;User Id=postgres;Password=postgres
      - Tenants__1__Name=Tenant B
      - Tenants__1__TenantId=tenant-b
      - Tenants__1__ConnectionString=Server=host.docker.internal;Port=5432;Database=payment-tenant-b;User Id=postgres;Password=postgres
    ports:
      - "5401:80"
      - "5400:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\Https:/https/:ro
    depends_on:
      - paymentdatabase

volumes:
  payment-database:
