version: "3.8"

services:
  identitydatabase:
    image: mysql
    container_name: identity_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: media
    volumes:
      - identity-database:/var/lib/mysql
    ports:
      - "5002:3306"

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    container_name: identity_service
    build:
      context: .
      dockerfile: Services/IdentityService/IdentityService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=mm-identity;password=passwd;port=5002;
      - JsonWebToken:Issuer=https://localhost:5000
    ports:
      - "5001:80"
      - "5000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - identitydatabase

volumes:
  identity-database:
