version: "3.8"

services:
  filedatabase:
    image: mysql
    container_name: file_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: mm-file
    volumes:
      - file-database:/var/lib/mysql
    ports:
      - "5302:3306"

  fileservice:
    image: ${DOCKER_REGISTRY-}fileservice
    container_name: file_service
    build:
      context: .
      dockerfile: Services/fileService/fileService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=mm-file;password=passwd;port=3306;
    ports:
      - "5301:80"
      - "5300:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - filedatabase

volumes:
  file-database:
