version: "3.8"

services:
  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: Services/OrderService/OrderService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=Server=host.docker.internal;Port=5434;Database=mm-payment;User Id=postgres;Password=postgres
    ports:
      - "5201:80"
      - "5200:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres
    networks:
      - postgres-network

  postgres:
    image: postgres:latest
    container_name: order_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: mm-payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge
