version: "3.8"

services:
  #######################################################
  # GATEWAYS
  #######################################################

  public_gateway:
    container_name: public_gateway
    build:
      context: ./Gateways/Public
      dockerfile: Dockerfile
    ports:
      - "9902:9902"
      - "10000:10000"
    networks:
      - everything

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: message-broker
  #   hostname: rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - everything

  # #######################################################
  # # Identity Service
  # #######################################################

  # identitydatabase:
  #   image: mysql
  #   container_name: identity_database
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: unless-stopped
  #   environment:
  #     - MYSQL_USER=admin
  #     - MYSQL_ROOT_PASSWORD=passwd
  #     - MYSQL_PASSWORD=passwd
  #     - MYSQL_DATABASE=media
  #   volumes:
  #     - identity-database:/var/lib/mysql
  #   networks:
  #     - everything

  # identityservice:
  #   image: ${DOCKER_REGISTRY-}identityservice
  #   container_name: identity_service
  #   build:
  #     context: .
  #     dockerfile: Services/IdentityService/IdentityService.API/Dockerfile.Development
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:443;http://+:80
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/IdentityService.pfx
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
  #     - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=identity;password=passwd;port=3306;
  #     - JsonWebToken:Issuer=https://host.docker.internal:5000
  #     - RabbitMq:Host=rabbitmq://host.docker.internal
  #     - RabbitMq:Username=guest
  #     - RabbitMq:Password=guest
  #     - Tenants__0__Name=Tenant A
  #     - Tenants__0__TenantId=tenant-a
  #     - Tenants__0__ConnectionString=server=host.docker.internal;user=root;database=identity-tenant-a;password=passwd;port=3306;
  #     - Tenants__1__Name=Tenant B
  #     - Tenants__1__TenantId=tenant-b
  #     - Tenants__1__ConnectionString=server=host.docker.internal;user=root;database=identity-tenant-b;password=passwd;port=3306;
  #   ports:
  #     - "5001:80"
  #     - "5000:443"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${USERPROFILE}\.aspnet\Https:/https/:ro
  #   depends_on:
  #     - identitydatabase
  #     - rabbitmq
  #     - public_gateway
  #   networks:
  #     - everything

  # # #######################################################
  # # # File Service
  # # #######################################################

  # filedatabase:
  #   image: mysql
  #   container_name: file_database
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: unless-stopped
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=passwd
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=passwd
  #     - MYSQL_RANDOM_ROOT_PASSWORD=passwd
  #     - MYSQL_DATABASE=tenant
  #   volumes:
  #     - file-database:/var/lib/mysql
  #   networks:
  #     - everything

  # fileservice:
  #   image: ${DOCKER_REGISTRY-}fileservice
  #   container_name: file_service
  #   build:
  #     context: .
  #     dockerfile: Services/FileService/FileService.API/Dockerfile.Development
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:443;http://+:80
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/FileService.pfx
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
  #     - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=file;password=passwd;port=3306;
  #     - RabbitMq:Host=rabbitmq://host.docker.internal
  #     - RabbitMq:Username=guest
  #     - RabbitMq:Password=guest
  #     - Tenants__0__Name=Tenant A
  #     - Tenants__0__TenantId=tenant-a
  #     - Tenants__0__ConnectionString=server=host.docker.internal;user=root;database=file-tenant-a;password=passwd;port=3306;
  #     - Tenants__1__Name=Tenant B
  #     - Tenants__1__TenantId=tenant-b
  #     - Tenants__1__ConnectionString=server=host.docker.internal;user=root;database=file-tenant-b;password=passwd;port=3306;
  #   ports:
  #     - "5301:80"
  #     - "5300:443"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${USERPROFILE}\.aspnet\Https:/https/:ro
  #   depends_on:
  #     - filedatabase
  #     - rabbitmq
  #     - public_gateway
  #   networks:
  #     - everything

  #######################################################
  # Catalog Service
  #######################################################

  catalog_cache:
    image: redis/redis-stack
    container_name: catalog_cache
    ports:
      - 5103:6379
      - 5104:8001
    networks:
      - everything

  catalog_database:
    image: mongo
    container_name: catalog_database
    restart: unless-stopped
    ports:
      - 5102:27017
    volumes:
      - catalog-database:/data/db
    networks:
      - everything

  catalog_service:
    image: ${DOCKER_REGISTRY-}catalogservice
    container_name: catalog_service
    build:
      context: .
      dockerfile: Services/CatalogService/CatalogService.API/Dockerfile.Development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/CatalogService.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - Cache__DefaultConnection=host.docker.internal
      - Cache__DefaultPort=5103
      - RabbitMq:Host=rabbitmq://host.docker.internal
      - RabbitMq:Username=guest
      - RabbitMq:Password=guest
      - Tenants__0__Name=Tenant A
      - Tenants__0__TenantId=tenant-a
      - Tenants__0__ConnectionString=mongodb://host.docker.internal:5102/
      - Tenants__1__Name=Tenant B
      - Tenants__1__TenantId=tenant-b
      - Tenants__1__ConnectionString=mongodb://host.docker.internal:5102/
    ports:
      - "5101:80"
      - "5100:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\Https:/https/:ro
    depends_on:
      - catalog_database
      - catalog_cache
      # - rabbitmq
      - public_gateway
    networks:
      - everything

networks:
  everything:

volumes:
  catalog-database:
  identity-database:
  file-database:
