version: "3.8"

services:
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
  # redisstack:
  #   container_name: redis_stack
  #   image: redis/redis-stack
  #   ports:
  #     - 8001:8001

  # basketdatabase:
  #   container_name: basket_database
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes:
  #     - basket-database:/data

  # basketservice:
  #   image: ${DOCKER_REGISTRY-}basketservice
  #   container_name: basket_service
  #   build:
  #     context: .
  #     dockerfile: Services/BasketService/BasketService.API/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:443;http://+:80
  #   ports:
  #     - "5701:80"
  #     - "5700:443"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  #   depends_on:
  #     - basketdatabase

volumes:
  basket-database:
    driver: local
