version: "3.8"

services:
  deliverydatabase:
    image: mongo
    container_name: delivery_database
    restart: unless-stopped
    volumes:
      - delivery-database:/data/db
    ports:
      - 5502:27017

  deliveryservice:
    image: ${DOCKER_REGISTRY-}deliveryservice
    container_name: delivery_service
    build:
      context: .
      dockerfile: Services/DeliveryService/DeliveryService.API/Dockerfile.Development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/DeliveryService.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - Tenants__0__Name=Tenant A
      - Tenants__0__TenantId=tenant-a
      - Tenants__0__ConnectionString=mongodb://host.docker.internal:5502/
      - Tenants__1__Name=Tenant B
      - Tenants__1__TenantId=tenant-b
      - Tenants__1__ConnectionString=mongodb://host.docker.internal:5502/
    ports:
      - "5501:80"
      - "5500:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\Https:/https/:ro
    depends_on:
      - deliverydatabase

volumes:
  delivery-database:
