version: "3.8"

services:
  identitydatabase:
    image: mysql
    container_name: identity_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_PASSWORD=passwd
      - MYSQL_DATABASE=media
    volumes:
      - identity-database:/var/lib/mysql

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    container_name: identity_service
    build:
      context: .
      dockerfile: Services/IdentityService/IdentityService.API/Dockerfile.Development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/IdentityService.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=identity;password=passwd;port=3306;
      - JsonWebToken:Issuer=https://localhost:5000
      - RabbitMq:Host=host.docker.internal
      - RabbitMq:Username=guest
      - RabbitMq:Password=guest
      - Tenants__0__Name=Tenant A
      - Tenants__0__TenantId=tenant-a
      - Tenants__0__ConnectionString=server=host.docker.internal;user=root;database=identity-tenant-a;password=passwd;port=3306;
      - Tenants__1__Name=Tenant B
      - Tenants__1__TenantId=tenant-b
      - Tenants__1__ConnectionString=server=host.docker.internal;user=root;database=identity-tenant-b;password=passwd;port=3306;
    ports:
      - "5001:80"
      - "5000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\Https:/https/:ro
    depends_on:
      - identitydatabase

volumes:
  identity-database:
