version: "3.8"

services:
  deliverydatabase:
    image: mongo
    container_name: delivery_database
    restart: unless-stopped
    ports:
      - 5502:27017
    volumes:
      - delivery-database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passwd

  deliveryservice:
    image: ${DOCKER_REGISTRY-}deliveryservice
    container_name: delivery_service
    build:
      context: .
      dockerfile: Services/DeliveryService/DeliveryService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=mongodb://admin:passwd@host.docker.internal:5502
      - ConnectionStrings:Database=mm-delivery
    ports:
      - "5501:80"
      - "5500:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - deliverydatabase

volumes:
  delivery-database:
