version: "3.8"

services:
  identitydatabase:
    image: postgres
    container_name: identity_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: mm-payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5002:5432"
    volumes:
      - identity-data:/var/lib/postgresql/data

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    container_name: identity_service
    build:
      context: .
      dockerfile: Services/IdentityService/IdentityService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=Server=host.docker.internal;Port=5002;Database=mm-identity;User Id=postgres;Password=postgres
    ports:
      - "5001:80"
      - "5000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - identitydatabase

volumes:
  identity-data:
