version: "3.8"

services:
  paymentdatabase:
    image: postgres
    container_name: payment_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5402:5432"
    volumes:
      - payment-database:/var/lib/postgresql/data
    networks:
      - payment-network

  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    container_name: payment_service
    build:
      context: .
      dockerfile: Services/PaymentService/PaymentService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=Server=host.docker.internal;Port=5402;Database=mm-payment;User Id=postgres;Password=postgres
    ports:
      - "5401:80"
      - "5400:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - paymentdatabase
    networks:
      - payment-network

volumes:
  payment-database:

networks:
  payment-network:
    driver: bridge
