version: "3.8"

services:
  tenantdatabase:
    image: mysql
    container_name: tenant_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: media
    volumes:
      - database:/var/lib/mysql
    ports:
      - "5202:3306"
    networks:
      - tenant-network

  tenantservice:
    image: ${DOCKER_REGISTRY-}tenantservice
    container_name: tenant_service
    build:
      context: .
      dockerfile: Services/TenantService/TenantService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=media;password=passwd;port=3306;
    ports:
      - "5201:80"
      - "5200:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - tenantdatabase
    networks:
      - tenant-network

volumes:
  database:

networks:
  tenant-network:
    driver: bridge
