version: "3.8"

services:
  basketdatabase:
    image: redis/redis-stack
    container_name: basket_database
    ports:
      - 5703:6379
      - 5704:8001
    volumes:
      - basket_data:/data

  basketservice:
    image: ${DOCKER_REGISTRY-}basketservice
    container_name: basket_service
    build:
      context: .
      dockerfile: Services/BasketService/BasketService.API/Dockerfile.Development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/BasketService.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ConnectionStrings__DefaultConnection=host.docker.internal:5703
      - Tenants__0__Name=Tenant A
      - Tenants__0__TenantId=tenant-a
      - Tenants__1__Name=Tenant B
      - Tenants__1__TenantId=tenant-b
    ports:
      - "5701:80"
      - "5700:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\Https:/https/:ro
    depends_on:
      - basketdatabase

volumes:
  basket_data:
