version: "3.8"

services:
  orderdatabase:
    image: postgres
    container_name: order_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: mm-payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5602:5432"
    volumes:
      - order-database:/var/lib/postgresql/data

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    container_name: order_service
    build:
      context: .
      dockerfile: Services/OrderService/OrderService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=Server=host.docker.internal;Port=5602;Database=mm-payment;User Id=postgres;Password=postgres
    ports:
      - "5601:80"
      - "5600:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - orderdatabase

volumes:
  order-database:
