version: "3.8"

services:
  tenantdatabase:
    image: mysql
    container_name: tenant_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=passwd
      - MYSQL_DATABASE=tenant
    volumes:
      - tenant-database:/var/lib/mysql

  tenantservice:
    image: ${DOCKER_REGISTRY-}tenantservice
    container_name: tenant_service
    build:
      context: .
      dockerfile: Services/TenantService/TenantService.API/Dockerfile.Development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/TenantService.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=tenant;password=passwd;port=3306;
      - Tenants__0__Name=Tenant A
      - Tenants__0__TenantId=tenant-a
      - Tenants__0__ConnectionString=server=host.docker.internal;user=root;database=tenant-tenant-a;password=passwd;port=3306;
      - Tenants__1__Name=Tenant B
      - Tenants__1__TenantId=tenant-b
      - Tenants__1__ConnectionString=server=host.docker.internal;user=root;database=tenant-tenant-b;password=passwd;port=3306;
    ports:
      - "5201:80"
      - "5200:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\Https:/https/:ro
    depends_on:
      - tenantdatabase

volumes:
  tenant-database:
