version: "3.8"

services:
  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=Server=host.docker.internal;Port=5432;Database=mm-orders;User Id=postgres;Password=postgres;
    ports:
      - "5201:80"
      - "5200:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres
    networks:
      - order-network

  postgres:
    image: postgres
    container_name: identity_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mm-orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - order-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  order-network:
    driver: bridge
