// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenantService.Infrastructure.Data;

#nullable disable

namespace TenantService.Infrastructure.Migrations
{
    [DbContext(typeof(TenantContext))]
    [Migration("20220613005957_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TenantService.Core.Domain.Aggregates.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DeliveryCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imprint")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFreeDelivery")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MinimunOrderAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("TenantService.Core.Domain.Aggregates.Tenant", b =>
                {
                    b.OwnsOne("TenantService.Core.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_street");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_zip");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsMany("TenantService.Core.Domain.ValueObjects.Workingday", "Workingdays", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Closing")
                                .HasColumnType("longtext")
                                .HasColumnName("closing");

                            b1.Property<bool>("IsClosedToday")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("Message")
                                .HasColumnType("longtext");

                            b1.Property<string>("Opening")
                                .HasColumnType("longtext")
                                .HasColumnName("opening");

                            b1.HasKey("TenantId", "Id");

                            b1.ToTable("Workingday");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("TenantService.Core.Domain.Enumerations.Weekday", "Weekday", b2 =>
                                {
                                    b2.Property<Guid>("WorkingdayTenantId")
                                        .HasColumnType("char(36)");

                                    b2.Property<int>("WorkingdayId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("longtext");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int");

                                    b2.HasKey("WorkingdayTenantId", "WorkingdayId");

                                    b2.ToTable("Workingday");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkingdayTenantId", "WorkingdayId");
                                });

                            b1.Navigation("Weekday")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Workingdays");
                });
#pragma warning restore 612, 618
        }
    }
}
