version: "3.8"

services:
  mediaservice:
    image: ${DOCKER_REGISTRY-}mediaservice
    build:
      context: .
      dockerfile: MediaService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=server=host.docker.internal;user=root;database=mm-media;password=passwd;port=3308;
    ports:
      - "5301:80"
      - "5300:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - mysql
    networks:
      - mysql-network

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: mm-media
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - mysql-network

volumes:
  mysql-db:

networks:
  mysql-network:
    driver: bridge
