version_info: "0"
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: identityservice
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: identityservice
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: identityservice
                    port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: catalogservice
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: catalogservice
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: catalogservice
                    port_value: 443

    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: deliveryservice
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: deliveryservice
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: deliveryservice
                    port_value: 443

    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
