version: "3.4"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_database_delivery
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongo-database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passwd

volumes:
  mongo-database:
