import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import React from "react"
import Header from "@/components/header"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="text-rose-500">test</div>
    </div>
  )
}

export default Home
