version: "3.4"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_database_catalog
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passwd

  catalogservice:
    image: ${DOCKER_REGISTRY-}catalogservice
    container_name: catalogservice
    build:
      context: .
      dockerfile: CatalogService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=mongodb://admin:passwd@host.docker.internal:27017
      - ConnectionStrings:Database=mm-catalog
    depends_on:
      - mongo
    ports:
      - 5601:80
      - 5600:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  mongo-database:
