version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: mm-tenant
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql-db:
