// <auto-generated />
using System;
using FileService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileService.Infrastructure.Migrations
{
    [DbContext(typeof(FileContext))]
    partial class FileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FileService.Core.Domain.Image.ImageFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ExternalEntityId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FileService.Core.Domain.Video.VideoFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ExternalEntityId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("FileService.Core.Domain.Image.ImageFile", b =>
                {
                    b.OwnsMany("FileService.Core.Domain.Image.ImageUrl", "Images", b1 =>
                        {
                            b1.Property<Guid>("ImageFileId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("Breakpoint")
                                .HasColumnType("int");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Height")
                                .HasColumnType("int");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Width")
                                .HasColumnType("int");

                            b1.HasKey("ImageFileId", "Id");

                            b1.ToTable("ImageUrl");

                            b1.WithOwner()
                                .HasForeignKey("ImageFileId");
                        });

                    b.Navigation("Images");
                });

            modelBuilder.Entity("FileService.Core.Domain.Video.VideoFile", b =>
                {
                    b.OwnsOne("FileService.Core.Domain.Video.VideoUrl", "Url", b1 =>
                        {
                            b1.Property<Guid>("VideoFileId")
                                .HasColumnType("char(36)");

                            b1.Property<double>("Duration")
                                .HasColumnType("double");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Height")
                                .HasColumnType("int");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Width")
                                .HasColumnType("int");

                            b1.HasKey("VideoFileId");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("VideoFileId");
                        });

                    b.Navigation("Url")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
