version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5005:80"
    networks:
      - catalog-network

  mongo:
    image: mongo
    container_name: catalog-mongo_container
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - catalog-network

volumes:
  mongodb-data:

networks:
  catalog-network:
    driver: bridge
