version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: mongo_container
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    

  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    container_name: catalogservice_container
    build:
      context: .
      dockerfile: CatalogService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings:DefaultConnection=mongodb://host.docker.internal:27017
      - ConnectionStrings:Database=TestProduct
      - ConnectionStrings:Collection=Catalog
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    ports:
      - 6003:80
      - 6002:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  mongodb-data: